In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('Dados/Heart_Disease_Prediction.csv')
norm = StandardScaler()

# df['Heart Disease'] = df['Heart Disease'].map(lambda x: 0 if x == 'Absence' else 1)
# corr_matrix = df.corr()['Heart Disease'].sort_values()
# corr_matrix

y = df['Heart Disease']
y = np.where(y == 'Presence', 1, 0)
X = df.drop(columns=['Heart Disease'])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

X_train = norm.fit_transform(X_train)
X_test = norm.fit_transform(X_test)


gnb = GaussianNB()
gnb.fit(X_train, y_train.ravel())

y_pred = gnb.predict(X_test)

confusion_matrix(y_test, y_pred)
# accuracy_score(y_test, y_pred)


array([[24,  6],
       [ 7, 17]])

In [79]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

df = pd.read_csv('Dados/music_data/Data/features_3_sec.csv')
norm = StandardScaler()
pca = PCA(n_components=10)
le = LabelEncoder()


target = 'label'
classes = list(set(df[target]))
y = le.fit_transform(df[target])

X = df.drop(columns = [target])
X = X.select_dtypes(include = ['number'])
X = norm.fit_transform(X) # Normalização para aplicação do PCA
X = pca.fit_transform(X) # Redução de dimensão para 4 atributos apenas

In [80]:
from sklearn.tree import export_graphviz
from sklearn.metrics import classification_report, confusion_matrix, cohen_kappa_score

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y, 
    test_size=0.2,       
    random_state=42,     
    stratify=y          
) # Divisão em seleção aleatório em cada subgrupo distinto

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
export_graphviz(dt, out_file='arvore.dot')

y = le.inverse_transform(y)

In [82]:
y_pred = dt.predict(X_test)

print(classification_report(y_test, y_pred, target_names = classes))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

      hiphop       0.54      0.56      0.55       200
        jazz       0.73      0.76      0.75       199
     country       0.46      0.39      0.43       199
       blues       0.45      0.53      0.48       200
        rock       0.61      0.56      0.59       200
      reggae       0.58      0.53      0.55       200
         pop       0.76      0.77      0.77       200
       metal       0.67      0.59      0.63       200
       disco       0.55      0.60      0.57       200
   classical       0.47      0.51      0.49       200

    accuracy                           0.58      1998
   macro avg       0.58      0.58      0.58      1998
weighted avg       0.58      0.58      0.58      1998

[[112   3  17  14   4  12   8   3  10  17]
 [  5 152   7   3   1  21   0   2   2   6]
 [ 31   7  78  13  11  16   2   8  15  18]
 [  8   2   6 105   9   4  19  11  20  16]
 [  7   1   7  20 113   0   4  15  26   7]
 [ 13  30  13   7   1 105 